server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521/ORCL
    username: rm98611
    password: 080404
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.Oracle12cDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
